name: Go package

on:
  push:
    paths:
      - "fieldcheck/go.mod"
      - "fieldcheck/**"
      - ".github/workflows/go.yml"
  pull_request:
    paths:
      - "fieldcheck/go.mod"
      - "fieldcheck/**"
      - ".github/workflows/go.yml"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: fieldcheck/go.mod
      - run: gofmt -d -e fieldcheck/*.go
      - run: go test ./...
        working-directory: fieldcheck
